package com.aleiye.adatav.entity;

public class DatavInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.DESCR
     *
     * @mbggenerated
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.DATA
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.IMAGE
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.TEMPLATE
     *
     * @mbggenerated
     */
    private Short template;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.WIDTH
     *
     * @mbggenerated
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.HEIGHT
     *
     * @mbggenerated
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.OWNER_ID
     *
     * @mbggenerated
     */
    private String ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.FOLDER_ID
     *
     * @mbggenerated
     */
    private String folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.FOLDER_NAME
     *
     * @mbggenerated
     */
    private String folderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Long modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_INFO.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.ID
     *
     * @return the value of DATAV_INFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.ID
     *
     * @param id the value for DATAV_INFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.NAME
     *
     * @return the value of DATAV_INFO.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.NAME
     *
     * @param name the value for DATAV_INFO.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.DESCR
     *
     * @return the value of DATAV_INFO.DESCR
     *
     * @mbggenerated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.DESCR
     *
     * @param descr the value for DATAV_INFO.DESCR
     *
     * @mbggenerated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.DATA
     *
     * @return the value of DATAV_INFO.DATA
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.DATA
     *
     * @param data the value for DATAV_INFO.DATA
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.IMAGE
     *
     * @return the value of DATAV_INFO.IMAGE
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.IMAGE
     *
     * @param image the value for DATAV_INFO.IMAGE
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.TEMPLATE
     *
     * @return the value of DATAV_INFO.TEMPLATE
     *
     * @mbggenerated
     */
    public Short getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.TEMPLATE
     *
     * @param template the value for DATAV_INFO.TEMPLATE
     *
     * @mbggenerated
     */
    public void setTemplate(Short template) {
        this.template = template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.WIDTH
     *
     * @return the value of DATAV_INFO.WIDTH
     *
     * @mbggenerated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.WIDTH
     *
     * @param width the value for DATAV_INFO.WIDTH
     *
     * @mbggenerated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.HEIGHT
     *
     * @return the value of DATAV_INFO.HEIGHT
     *
     * @mbggenerated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.HEIGHT
     *
     * @param height the value for DATAV_INFO.HEIGHT
     *
     * @mbggenerated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.OWNER_ID
     *
     * @return the value of DATAV_INFO.OWNER_ID
     *
     * @mbggenerated
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.OWNER_ID
     *
     * @param ownerId the value for DATAV_INFO.OWNER_ID
     *
     * @mbggenerated
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.FOLDER_ID
     *
     * @return the value of DATAV_INFO.FOLDER_ID
     *
     * @mbggenerated
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.FOLDER_ID
     *
     * @param folderId the value for DATAV_INFO.FOLDER_ID
     *
     * @mbggenerated
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.FOLDER_NAME
     *
     * @return the value of DATAV_INFO.FOLDER_NAME
     *
     * @mbggenerated
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.FOLDER_NAME
     *
     * @param folderName the value for DATAV_INFO.FOLDER_NAME
     *
     * @mbggenerated
     */
    public void setFolderName(String folderName) {
        this.folderName = folderName == null ? null : folderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.CREATE_TIME
     *
     * @return the value of DATAV_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.CREATE_TIME
     *
     * @param createTime the value for DATAV_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.MODIFY_TIME
     *
     * @return the value of DATAV_INFO.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.MODIFY_TIME
     *
     * @param modifyTime the value for DATAV_INFO.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_INFO.STATUS
     *
     * @return the value of DATAV_INFO.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_INFO.STATUS
     *
     * @param status the value for DATAV_INFO.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}