package com.aleiye.adatav.entity;

public class DatavComponent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.DATAV_ID
     *
     * @mbggenerated
     */
    private String datavId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.DESCR
     *
     * @mbggenerated
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.DATA
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.OWNER_ID
     *
     * @mbggenerated
     */
    private String ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.CREATE_TIME
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Long modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATAV_COMPONENT.STATUS
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * 是否为创建
     */
    private boolean create;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.ID
     *
     * @return the value of DATAV_COMPONENT.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.ID
     *
     * @param id the value for DATAV_COMPONENT.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.DATAV_ID
     *
     * @return the value of DATAV_COMPONENT.DATAV_ID
     *
     * @mbggenerated
     */
    public String getDatavId() {
        return datavId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.DATAV_ID
     *
     * @param datavId the value for DATAV_COMPONENT.DATAV_ID
     *
     * @mbggenerated
     */
    public void setDatavId(String datavId) {
        this.datavId = datavId == null ? null : datavId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.NAME
     *
     * @return the value of DATAV_COMPONENT.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.NAME
     *
     * @param name the value for DATAV_COMPONENT.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.DESCR
     *
     * @return the value of DATAV_COMPONENT.DESCR
     *
     * @mbggenerated
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.DESCR
     *
     * @param descr the value for DATAV_COMPONENT.DESCR
     *
     * @mbggenerated
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.TYPE
     *
     * @return the value of DATAV_COMPONENT.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.TYPE
     *
     * @param type the value for DATAV_COMPONENT.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.DATA
     *
     * @return the value of DATAV_COMPONENT.DATA
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.DATA
     *
     * @param data the value for DATAV_COMPONENT.DATA
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.OWNER_ID
     *
     * @return the value of DATAV_COMPONENT.OWNER_ID
     *
     * @mbggenerated
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.OWNER_ID
     *
     * @param ownerId the value for DATAV_COMPONENT.OWNER_ID
     *
     * @mbggenerated
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.CREATE_TIME
     *
     * @return the value of DATAV_COMPONENT.CREATE_TIME
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.CREATE_TIME
     *
     * @param createTime the value for DATAV_COMPONENT.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.MODIFY_TIME
     *
     * @return the value of DATAV_COMPONENT.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.MODIFY_TIME
     *
     * @param modifyTime the value for DATAV_COMPONENT.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATAV_COMPONENT.STATUS
     *
     * @return the value of DATAV_COMPONENT.STATUS
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATAV_COMPONENT.STATUS
     *
     * @param status the value for DATAV_COMPONENT.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    public boolean getCreate() {
        return create;
    }

    public void setCreate(boolean create) {
        this.create = create;
    }
}