package com.aleiye.adatav.dao;

import com.aleiye.adatav.entity.DatavFolder;
import com.aleiye.adatav.entity.DatavFolderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DatavFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int countByExample(DatavFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int deleteByExample(DatavFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int insert(DatavFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int insertSelective(DatavFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    List<DatavFolder> selectByExample(DatavFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    DatavFolder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DatavFolder record, @Param("example") DatavFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DatavFolder record, @Param("example") DatavFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DatavFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_FOLDER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DatavFolder record);
}