package com.aleiye.adatav.dao;

import com.aleiye.adatav.entity.DatavComponent;
import com.aleiye.adatav.entity.DatavComponentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DatavComponentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int countByExample(DatavComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int deleteByExample(DatavComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int insert(DatavComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int insertSelective(DatavComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    List<DatavComponent> selectByExample(DatavComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    DatavComponent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DatavComponent record, @Param("example") DatavComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DatavComponent record, @Param("example") DatavComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DatavComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATAV_COMPONENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DatavComponent record);
}